#!/bin/sh

while getopts "a:m:y:" OPTION
do
    case $OPTION in
        a)
            echo "Starting merge process for year {$OPTARG} ..."

            echo "Merging for Jan ..."
            cdo mergetime 3B-HHR.MS.MRG.3IMERG."$OPTARG"01*.nc4 gpm_"$OPTARG"_01.nc4 2> /dev/null
            echo "Finished Merging for Jan ..."
            sleep 15

            echo "Merging for Feb ..."
            cdo mergetime 3B-HHR.MS.MRG.3IMERG."$OPTARG"02*.nc4 gpm_"$OPTARG"_02.nc4 2> /dev/null
            echo "Finished Merging for Feb ..."
            sleep 15

            echo "Merging for Mar ..."
            cdo mergetime 3B-HHR.MS.MRG.3IMERG."$OPTARG"03*.nc4 gpm_"$OPTARG"_03.nc4 2> /dev/null
            echo "Finished Merging for Mar ..."
            sleep 15

            echo "Merging for Apr ..."
            cdo mergetime 3B-HHR.MS.MRG.3IMERG."$OPTARG"04*.nc4 gpm_"$OPTARG"_04.nc4 2> /dev/null
            echo "Finished Merging for Apr ..."
            sleep 15

            echo "Merging for May ..."
            cdo mergetime 3B-HHR.MS.MRG.3IMERG."$OPTARG"05*.nc4 gpm_"$OPTARG"_05.nc4 2> /dev/null
            echo "Finished Merging for May ..."
            sleep 15

            echo "Merging for Jun ..."
            cdo mergetime 3B-HHR.MS.MRG.3IMERG."$OPTARG"06*.nc4 gpm_"$OPTARG"_06.nc4 2> /dev/null
            echo "Finished Merging for Jun ..."
            sleep 15

            echo "Merging for Jul ..."
            cdo mergetime 3B-HHR.MS.MRG.3IMERG."$OPTARG"07*.nc4 gpm_"$OPTARG"_07.nc4 2>/dev/null
            echo "Finished Merging for Jul ..."
            sleep 15

            echo "Merging for Aug ..."
            cdo mergetime 3B-HHR.MS.MRG.3IMERG."$OPTARG"08*.nc4 gpm_"$OPTARG"_08.nc4 2> /dev/null
            echo "Finished Merging for Aug ..."
            sleep 15

            echo "Merging for Sept ..."
            cdo mergetime 3B-HHR.MS.MRG.3IMERG."$OPTARG"09*.nc4 gpm_"$OPTARG"_09.nc4 2> /dev/null
            echo "Finished Merging for Sept ..."
            sleep 15

            echo "Merging for Oct ..."
            cdo mergetime 3B-HHR.MS.MRG.3IMERG."$OPTARG"10*.nc4 gpm_"$OPTARG"_10.nc4 2> /dev/null
            echo "Finished Merging for Oct ..."
            sleep 15

            echo "Merging for Nov ..."
            cdo mergetime 3B-HHR.MS.MRG.3IMERG."$OPTARG"11*.nc4 gpm_"$OPTARG"_11.nc4 2> /dev/null
            echo "Finished Merging for Nov ..."
            sleep 15

            echo "Merging for Dec ..."
            cdo mergetime 3B-HHR.MS.MRG.3IMERG."$OPTARG"12*.nc4 gpm_"$OPTARG"_12.nc4 2> /dev/null
            echo "Finished Merging for Dec ..."
            sleep 20

            echo "Now Merging for All months ..."
            cdo mergetime gpm_"$OPTARG"_*.nc4 gpm_"$OPTARG".nc

            echo "Finished the merging process"
            exit
            ;;

        m)
            echo "Starting merge process for year {$OPTARG} ..."

            echo "Merging for Jan ..."
            cdo mergetime 3B-HHR.MS.MRG.3IMERG."$OPTARG"01*.nc4 gpm_"$OPTARG"_01.nc4 2> /dev/null
            echo "Finished Merging for Jan ..."
            sleep 15

            echo "Merging for Feb ..."
            cdo mergetime 3B-HHR.MS.MRG.3IMERG."$OPTARG"02*.nc4 gpm_"$OPTARG"_02.nc4 2> /dev/null
            echo "Finished Merging for Feb ..."
            sleep 15

            echo "Merging for Mar ..."
            cdo mergetime 3B-HHR.MS.MRG.3IMERG."$OPTARG"03*.nc4 gpm_"$OPTARG"_03.nc4 2> /dev/null
            echo "Finished Merging for Mar ..."
            sleep 15

            echo "Merging for Apr ..."
            cdo mergetime 3B-HHR.MS.MRG.3IMERG."$OPTARG"04*.nc4 gpm_"$OPTARG"_04.nc4 2> /dev/null
            echo "Finished Merging for Apr ..."
            sleep 15

            echo "Merging for May ..."
            cdo mergetime 3B-HHR.MS.MRG.3IMERG."$OPTARG"05*.nc4 gpm_"$OPTARG"_05.nc4 2> /dev/null
            echo "Finished Merging for May ..."
            sleep 15

            echo "Merging for Jun ..."
            cdo mergetime 3B-HHR.MS.MRG.3IMERG."$OPTARG"06*.nc4 gpm_"$OPTARG"_06.nc4 2> /dev/null
            echo "Finished Merging for Jun ..."
            sleep 15

            echo "Merging for Jul ..."
            cdo mergetime 3B-HHR.MS.MRG.3IMERG."$OPTARG"07*.nc4 gpm_"$OPTARG"_07.nc4 2>/dev/null
            echo "Finished Merging for Jul ..."
            sleep 15

            echo "Merging for Aug ..."
            cdo mergetime 3B-HHR.MS.MRG.3IMERG."$OPTARG"08*.nc4 gpm_"$OPTARG"_08.nc4 2> /dev/null
            echo "Finished Merging for Aug ..."
            sleep 15

            echo "Merging for Sept ..."
            cdo mergetime 3B-HHR.MS.MRG.3IMERG."$OPTARG"09*.nc4 gpm_"$OPTARG"_09.nc4 2> /dev/null
            echo "Finished Merging for Sept ..."
            sleep 15

            echo "Merging for Oct ..."
            cdo mergetime 3B-HHR.MS.MRG.3IMERG."$OPTARG"10*.nc4 gpm_"$OPTARG"_10.nc4 2> /dev/null
            echo "Finished Merging for Oct ..."
            sleep 15

            echo "Merging for Nov ..."
            cdo mergetime 3B-HHR.MS.MRG.3IMERG."$OPTARG"11*.nc4 gpm_"$OPTARG"_11.nc4 2> /dev/null
            echo "Finished Merging for Nov ..."
            sleep 15

            echo "Merging for Dec ..."
            cdo mergetime 3B-HHR.MS.MRG.3IMERG."$OPTARG"12*.nc4 gpm_"$OPTARG"_12.nc4 2> /dev/null
            echo "Finished Merging for Dec ..."

            echo "Finished the merging process"
            exit
            ;;
        y)
            echo "Starting merge process for year {$OPTARG} ..."

            echo "Now Merging for All months ..."
            cdo mergetime gpm_"$OPTARG"_*.nc4 gpm_"$OPTARG".nc

            echo "Finished the merging process"
            exit
            ;;
    esac
done
